<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Photos extends \App\Model\Database\Entity\Photos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'archiveFilename', 'originalFilename', 'jp2Filename', 'herbarium', 'status', 'specimenId', 'width', 'height', 'archiveFileSize', 'JP2FileSize', 'message', 'thumbnail', 'exif', 'identify', 'id', 'createdAt', 'lastEdit', 'originalFileTimestamp'];
        }

        return ['__isInitialized__', 'archiveFilename', 'originalFilename', 'jp2Filename', 'herbarium', 'status', 'specimenId', 'width', 'height', 'archiveFileSize', 'JP2FileSize', 'message', 'thumbnail', 'exif', 'identify', 'id', 'createdAt', 'lastEdit', 'originalFileTimestamp'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Photos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getArchiveFilename(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchiveFilename', []);

        return parent::getArchiveFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchiveFilename(string $archiveFilename): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchiveFilename', [$archiveFilename]);

        return parent::setArchiveFilename($archiveFilename);
    }

    /**
     * {@inheritDoc}
     */
    public function getJp2Filename(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJp2Filename', []);

        return parent::getJp2Filename();
    }

    /**
     * {@inheritDoc}
     */
    public function setJp2Filename(string $jp2Filename): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJp2Filename', [$jp2Filename]);

        return parent::setJp2Filename($jp2Filename);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidth(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidth', []);

        return parent::getWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidth(?int $width): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidth', [$width]);

        return parent::setWidth($width);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeight(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeight', []);

        return parent::getHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeight(?int $height): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeight', [$height]);

        return parent::setHeight($height);
    }

    /**
     * {@inheritDoc}
     */
    public function getArchiveFileSize(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchiveFileSize', []);

        return parent::getArchiveFileSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchiveFileSize(?int $archiveFileSize): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchiveFileSize', [$archiveFileSize]);

        return parent::setArchiveFileSize($archiveFileSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getJp2FileSize(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJp2FileSize', []);

        return parent::getJp2FileSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setJp2FileSize(?int $JP2FileSize): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJp2FileSize', [$JP2FileSize]);

        return parent::setJp2FileSize($JP2FileSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', []);

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage(?string $message): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', [$message]);

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullSpecimenId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullSpecimenId', []);

        return parent::getFullSpecimenId();
    }

    /**
     * {@inheritDoc}
     */
    public function getHerbarium(): \App\Model\Database\Entity\Herbaria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHerbarium', []);

        return parent::getHerbarium();
    }

    /**
     * {@inheritDoc}
     */
    public function setHerbarium(\App\Model\Database\Entity\Herbaria $herbarium): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHerbarium', [$herbarium]);

        return parent::setHerbarium($herbarium);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecimenId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecimenId', []);

        return parent::getSpecimenId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecimenId(?string $specimenId): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecimenId', [$specimenId]);

        return parent::setSpecimenId($specimenId);
    }

    /**
     * {@inheritDoc}
     */
    public function getJacqPid(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJacqPid', []);

        return parent::getJacqPid();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): \App\Model\Database\Entity\PhotosStatus
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(\App\Model\Database\Entity\PhotosStatus $status): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalFilename(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalFilename', []);

        return parent::getOriginalFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalFilename(string $originalFilename): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalFilename', [$originalFilename]);

        return parent::setOriginalFilename($originalFilename);
    }

    /**
     * {@inheritDoc}
     */
    public function getThumbnail(): mixed
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThumbnail', []);

        return parent::getThumbnail();
    }

    /**
     * {@inheritDoc}
     */
    public function setThumbnail(mixed $thumbnail): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThumbnail', [$thumbnail]);

        return parent::setThumbnail($thumbnail);
    }

    /**
     * {@inheritDoc}
     */
    public function getExif(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExif', []);

        return parent::getExif();
    }

    /**
     * {@inheritDoc}
     */
    public function setExif(?array $exif): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExif', [$exif]);

        return parent::setExif($exif);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentify(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentify', []);

        return parent::getIdentify();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentify(?array $identify): \App\Model\Database\Entity\Photos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentify', [$identify]);

        return parent::setIdentify($identify);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): \DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(): mixed
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', []);

        return parent::setCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastEditAt(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastEditAt', []);

        return parent::getLastEditAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastEditAt(): mixed
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastEditAt', []);

        return parent::setLastEditAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalFileAt(): ?\DateTimeImmutable
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalFileAt', []);

        return parent::getOriginalFileAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalFileAt(?\DateTimeImmutable $timestamp): mixed
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalFileAt', [$timestamp]);

        return parent::setOriginalFileAt($timestamp);
    }

}
